version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapegraph_server_environment
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
